# Generated by Django 5.1.7 on 2025-03-24 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='good_student',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
