# Generated by Django 5.1.7 on 2025-03-27 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0002_grade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grade',
            old_name='subject',
            new_name='a_subject',
        ),
    ]
