# Generated by Django 5.1.7 on 2025-03-27 21:20

import student_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0003_rename_subject_grade_a_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='professor',
            field=models.CharField(default='Mr. Cahan', validators=[student_app.validators.validate_professor]),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_name',
            field=models.CharField(default='Unknown', unique=True, validators=[student_app.validators.validate_subject]),
        ),
    ]
