# Generated by Django 5.1.7 on 2025-03-26 15:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0005_alter_student_good_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='subjects',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)]),
        ),
    ]
